#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# Use Homebrew to install base applications
cd brew
brew bundle

cd "$(dirname $0)"/..

# Retrieve antigen as a git submodule
git submodule init

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
