set locale-settings="LC_ALL=\"en_US.UTF-8\" LANG=\"en_US.UTF-8\""
alias pelican="${locale-settings} pelican"
alias pelican-quickstart="${locale-settings} pelican-quickstart"
alias pelican-make-html="${locale-settings} make html"
alias pelican-make-serve="${locale-settings} make serve"
alias pelican-make-regenerate="${locale-settings} make regenerate"
